
import { UF_FIELD_CONFIG } from "../config";
import { FaDeleteLeft } from "react-icons/fa6";
import { IoMdAdd, IoIosArrowUp, IoIosArrowDown } from "react-icons/io";
import { TbForbid } from "react-icons/tb";

import { useState, useEffect, useRef } from "react";
import Listener from "../listener";



const TextInput = ({ id, line, field, maxLength, readOnly, autogenerated, tableValueStore }) => {
    const [internalValue, setInternalValue] = useState(
        autogenerated ? "AUTOGEN" : line[field]
    );
    const [blinkClass, setBlinkClass] = useState('');

    useEffect(() => {
        setInternalValue(autogenerated ? "AUTOGEN" : line[field]);
    }, [line])

    const ref = useRef();

    const changed = (e) => {
        setInternalValue(e.target.value);
    }
    const unfocus = () => {
        if (internalValue !== line[field]) {
            setBlinkClass('blink-orange');
            setTimeout(() => setBlinkClass(''), 2000);
        }
        setInternalValue(line[field]);
    }
    const keyEvent = (e) => {
        if (e.key === 'Enter') {
            line[field] = internalValue
            tableValueStore(id, internalValue);
            setBlinkClass('blink-green');
            setTimeout(() => setBlinkClass(''), 2000);
        } else if (e.key === "Escape") {
            unfocus()
            if (ref.current)
                ref.current.blur();
        }
    }

    return <input ref={ref} value={internalValue} maxLength={maxLength} readOnly={readOnly} onChange={readOnly ? undefined : changed} onBlur={readOnly ? undefined : unfocus} onKeyDown={readOnly ? undefined : keyEvent} className={blinkClass}/>
}

const Table = ({ data, fields, name }) => {
    const [forceUpdate, setForceUpdate] = useState(new Date)
    useEffect(() => { }, [forceUpdate])

    const isDeletable = UF_FIELD_CONFIG[name]?.deletable;

    const removeEntityRow = (rowId) => {
        Listener.worker(["REMOVE", UF_FIELD_CONFIG[name].name, rowId]);
    };

    const tableInputStore = (id, value) => {
        //console.log(`Changed field ${id.index} ${id.index2}: ${value}`)
    }

    return (
        <div className="ufile_table_component">
            <div className="ufile_table_col" style={{ minWidth: "30px", width: "70px" }}>
                <div className="ufile_table_legend_field" />
                <div className="ufile_table_data">
                    {
                        data?.map((_, index) =>
                            <div
                                className="ufile_table_data_row"
                                key={`Delete_${index}`}
                                style={{ justifyContent: "center" }}
                                onClick={() => {
                                    if (isDeletable) {
                                        removeEntityRow(index)
                                    }
                                }}
                            >
                                {
                                    isDeletable ?
                                    <FaDeleteLeft color={"#fff"} size={"20px"} />
                                    :
                                    <TbForbid color={"#fcc603"} size={"20px"}/>
                                }

                            </div>
                        )
                    }
                </div>
            </div>
            <div className="ufile_table_col" style={{ minWidth: "30px", width: "70px" }}>
                <div className="ufile_table_legend_field"><p>Nr.</p></div>
                <div className="ufile_table_data">
                    {
                        data?.map((_, index) =>
                            <div
                                className="ufile_table_data_row"
                                key={`idx_${index}`}
                                style={{ justifyContent: "center" }}
                            >
                                {index + 1}
                            </div>
                        )
                    }
                </div>
            </div>
            {
                Object.keys(fields)?.map((field, index) =>
                    <div className="ufile_table_col" key={`table_col_${name}_${index}`}>
                        <div className="ufile_table_legend_field"><p>{fields[field].name}</p></div>
                        <div className="ufile_table_data">
                            {
                                data?.map((line, index2) =>
                                    <div className="ufile_table_data_row" key={`${name}_${index}_${index2}`}>
                                        {
                                            <TextInput id={{ index, index2 }} tableValueStore={tableInputStore} line={line} field={field} maxLength={fields[field].max} readOnly={fields[field]?.readOnly} autogenerated={fields[field]?.autogenerated}/>
                                            // fields[field]?.type === "select" ?
                                            //     <select className="ufile_table_select">
                                            //         {
                                            //             fields[field].options.map((option, index3) =>
                                            //                 <option key={`${name}_${index}_${index2}_${index3}`} value={option}>{actions[option]}</option>
                                            //             )
                                            //         }
                                            //     </select>
                                            //     :

                                        }
                                    </div>
                                )
                            }
                        </div>
                    </div>
                )
            }
        </div>
    );
}

const TableEntity = ({ name, data, search }) => {
    const [show, toggleShow] = useState(false);

    useEffect(() => {
        toggleShow(data?.length > 0);
    }, [data]);

    const fields = UF_FIELD_CONFIG[name].fields;
    const isDeletable = UF_FIELD_CONFIG[name].deletable;

    const parsedData = data.filter(parsedLine => {
        // Convert the parsedLine object to an array of its values, then convert that array to a string
        const parsedLineString = Object.values(parsedLine).join(' ');
        // Return true if the parsedLineString includes the search string, and false otherwise
        return parsedLineString.includes(search);
    });

    const addEntityRow = () => {
        Listener.worker(["ADD", UF_FIELD_CONFIG[name].name, ""])
    };
    const setHideTable = () => {
        toggleShow(prev => !prev);
    };

    return (
        <div
            className="ufile_table_entity"
            id={`ufile_table_entity_${name}`}
        >
            <header>
                <button
                    onClick={() => setHideTable()}
                    style={{ width: "25px", background: "#0c111c" }}
                >
                    {
                        show ?
                            <IoIosArrowUp size={"20px"} />
                            :
                            <IoIosArrowDown size={"20px"} />
                    }
                </button>
                {
                    isDeletable && <button onClick={() => addEntityRow()}><IoMdAdd size={"20px"} /></button>
                }
                <p>{`${name} [ ${parsedData?.length} ]`}</p>
            </header>
            {
                show && data && <Table data={parsedData} fields={fields} name={name} />
            }
        </div>
    );
}
export default TableEntity;